import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../constants/app_strings.dart';

/// App-wide translator. pt-BR is the product's default language; en/es are
/// offered through the Settings screen. [languageNotifier] lets widgets
/// rebuild reactively when the user switches language without pulling in a
/// state-management package, matching this project's existing DI-by-static-class style.
class Translator {
  Translator._();

  static const String _prefsKey = 'app_language';
  static const String defaultLanguage = 'pt';
  static const Set<String> supportedLanguages = {'pt', 'en', 'es'};

  static final ValueNotifier<String> languageNotifier = ValueNotifier(defaultLanguage);

  static String get currentLanguage => languageNotifier.value;

  /// Synchronous setter kept for tests and simple in-memory switches.
  /// Prefer [setLanguage] in the app so the preference is persisted.
  static set currentLanguage(String language) {
    languageNotifier.value = language;
  }

  /// Loads the persisted language preference. Call once during app startup,
  /// before the first screen is built.
  static Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_prefsKey);
    if (saved != null && supportedLanguages.contains(saved)) {
      languageNotifier.value = saved;
    }
  }

  /// Updates the current language and persists it locally.
  /// Does not call the backend — callers that need the preference synced
  /// server-side (e.g. the Settings screen) should do that separately.
  static Future<void> setLanguage(String language) async {
    if (!supportedLanguages.contains(language)) return;
    languageNotifier.value = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, language);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'pt': {
      AppStrings.welcomeBack: "Bem-vindo de volta",
      AppStrings.loginToContinue: "Faça login para continuar",
      AppStrings.emailOrUserHint: "E-mail ou Usuário",
      AppStrings.passwordHint: "Senha",
      AppStrings.forgotPassword: "Esqueceu a senha?",
      AppStrings.noAccountSignUp: "Não tem conta? Cadastre-se",
      AppStrings.loginButton: "Entrar",
      AppStrings.createAccount: "Criar Conta",
      AppStrings.fillDetails: "Preencha seus dados",
      AppStrings.nameHint: "Nome Completo",
      AppStrings.confirmPasswordHint: "Confirmar Senha",
      AppStrings.signupButton: "Cadastrar",
      AppStrings.alreadyHaveAccount: "Já tem conta? Entrar",

      AppStrings.pleaseAnswerAllQuestions: "Responda todas as perguntas",
      AppStrings.onboardingFailed: "Falha ao enviar respostas",
      AppStrings.noQuestionsAvailable: "Nenhuma pergunta disponível.",
      AppStrings.failedToLoadQuestions: "Falha ao carregar perguntas",

      AppStrings.petProfileTitle: "Perfil do PET",
      AppStrings.failedToSavePet: "Falha ao salvar o pet",

      AppStrings.meetPetTitle: "Conheça seu Companheiro",
      AppStrings.meetPetGreeting: "Olá!",
      AppStrings.meetPetIntro: "Sou o seu companheiro financeiro. Vou te ajudar a aprender sobre investimentos, manter a disciplina e comemorar cada conquista da sua jornada.",
      AppStrings.meetPetNeedName: "Mas antes... eu preciso de um nome!",
      AppStrings.meetPetSpeciesPrompt: "Escolha a espécie do seu companheiro",
      AppStrings.meetPetContinue: "Vamos começar!",
      AppStrings.meetPetPreviewTitle: "O que vamos fazer juntos",
      AppStrings.meetPetPreviewCelebrate: "Comemorar cada conquista da sua jornada",
      AppStrings.meetPetPreviewLearn: "Aprender sobre investimentos no seu ritmo",
      AppStrings.meetPetPreviewRemember: "Lembrar dos momentos importantes da nossa jornada",

      AppStrings.namePetTitle: "Escolha o Nome do seu Pet",
      AppStrings.namePetPrompt: "Como você gostaria de chamar seu companheiro?",
      AppStrings.namePetHint: "Nome do companheiro",
      AppStrings.namePetContinue: "Continuar",
      AppStrings.namePetReaction: "Adorei meu novo nome! Vamos começar sua jornada!",
      AppStrings.namePetRequiredError: "Escolha um nome para continuar",

      AppStrings.financialGoalTitle: "Qual será sua primeira missão?",
      AppStrings.financialGoalSubtitle: "Escolha o que você quer alcançar. Você pode mudar isso depois.",
      AppStrings.financialGoalContinue: "Continuar",

      AppStrings.onboardingSkip: "Pular",
      AppStrings.onboardingNext: "Próximo",

      AppStrings.welcomeHeadline: "Sua jornada financeira começa aqui.",
      AppStrings.welcomeSubheadline: "Aprenda. Invista. Evolua.",
      AppStrings.welcomeBody: "Transforme conhecimento financeiro em progresso de verdade.",
      AppStrings.welcomeCta: "Começar",

      AppStrings.academyIntroTitle: "Aprenda no seu ritmo.",
      AppStrings.academyIntroSubtitle: "Conhecimento antes de investir.",
      AppStrings.academyIntroBody: "Lições curtas, desafios e quizzes para você realmente entender de investimentos.",
      AppStrings.academyIntroXpBadge: "+{xp} XP por lição concluída",

      AppStrings.gamificationIntroTitle: "Aprenda. Jogue. Evolua.",
      AppStrings.gamificationIntroSubtitle: "Transforme conhecimento em progresso.",
      AppStrings.onboardingLevelBadge: "Nível {level}",

      AppStrings.missionCompleteLabel: "Missão Concluída",
      AppStrings.missionCompoundInterestTitle: "Aprenda sobre juros compostos",

      AppStrings.timeHorizonTitle: "Quando você quer alcançar isso?",
      AppStrings.timeHorizonSubtitle: "Isso ajusta o ritmo da sua jornada — você pode mudar depois.",

      AppStrings.journeyReadyTitle: "Sua jornada está pronta.",
      AppStrings.journeyReadySubtitle: "Agora é hora de começar a evoluir.",
      AppStrings.journeyReadyGoalLabel: "Seu objetivo",
      AppStrings.journeyReadyPathLabel: "Seu caminho",
      AppStrings.journeyReadyPathValue: "Aprender a Investir",
      AppStrings.journeyReadyCompanionLabel: "Seu companheiro",
      AppStrings.journeyReadyProgressLabel: "Seu progresso",
      AppStrings.journeyReadyFirstMissionLabel: "Sua primeira missão",
      AppStrings.journeyReadyCta: "Iniciar Minha Jornada",

      AppStrings.portfolioChoiceTitle: "Quer conectar seus investimentos agora?",
      AppStrings.portfolioChoiceBody: "Você pode importar seu portfólio automaticamente, adicionar manualmente, ou pular por enquanto. Você sempre pode fazer isso depois.",
      AppStrings.portfolioChoiceFootnote: "Não há pressa — {petName} vai estar aqui quando você estiver pronto.",
      AppStrings.importPortfolioButton: "Importar Portfólio",
      AppStrings.addManuallyButton: "Adicionar Manualmente",
      AppStrings.skipForNowButton: "Pular por Enquanto",
      AppStrings.importComingSoonTitle: "Em breve",
      AppStrings.importComingSoonBody: "A importação automática (B3, corretoras, CSV) ainda está sendo construída. Por enquanto, você pode adicionar seus ativos manualmente ou pular esta etapa.",
      AppStrings.okButton: "Entendi",

      AppStrings.portfolioNotConnectedTitle: "Portfólio ainda não conectado",
      AppStrings.portfolioNotConnectedBody: "Conecte seus investimentos quando estiver pronto — sem pressa.",
      AppStrings.connectInvestmentsButton: "Conectar Investimentos",
      AppStrings.suggestedActionsTitle: "O que fazer agora",
      AppStrings.suggestedActionCompleteLesson: "Concluir sua primeira lição",
      AppStrings.suggestedActionTodayMission: "Concluir a missão de hoje",
      AppStrings.suggestedActionLearnDividends: "Aprender sobre dividendos",
      AppStrings.suggestedActionFirstQuiz: "Fazer seu primeiro quiz",
      AppStrings.suggestedActionInvestorProfile: "Completar seu perfil de investidor",
      AppStrings.comingSoonSnack: "Em construção — em breve!",

      AppStrings.portfolioReminderMessage: "Percebi que ainda não conectamos seus investimentos. Quando você quiser, posso analisar seu portfólio e criar missões personalizadas. Não há pressa.",
      AppStrings.portfolioReminderCta: "Conectar agora",
      AppStrings.portfolioReminderDismiss: "Agora não",

      AppStrings.companionSectionTitle: "Companheiro",
      AppStrings.renamePetLabel: "Nome do companheiro",
      AppStrings.renamePetButton: "Renomear",
      AppStrings.renamePetDialogTitle: "Renomear companheiro",
      AppStrings.renamePetSuccess: "Nome atualizado!",

      AppStrings.settingsTitle: "Configurações",
      AppStrings.settingsSubtitle: "Personalize sua experiência, Comandante.",
      AppStrings.languageSectionTitle: "Idioma",
      AppStrings.languagePt: "Português (Brasil)",
      AppStrings.languageEn: "English",
      AppStrings.languageEs: "Español",
      AppStrings.languageUpdated: "Idioma atualizado",
      AppStrings.appearanceSectionTitle: "Aparência",
      AppStrings.appearanceLightLabel: "Claro",
      AppStrings.appearanceLightDescription: "Brilhante, limpo e acolhedor",
      AppStrings.appearanceDarkLabel: "Escuro",
      AppStrings.appearanceDarkDescription: "Premium, imersivo e futurista",
      AppStrings.appearanceSystemLabel: "Sistema",
      AppStrings.appearanceSystemDescription: "Segue as configurações do aparelho",
      AppStrings.appearanceUpdated: "Aparência atualizada",
      AppStrings.notificationsSectionTitle: "Notificações",
      AppStrings.dailyMissionReminders: "Lembretes de missões diárias",
      AppStrings.achievementAlerts: "Alertas de conquistas",
      AppStrings.privacySectionTitle: "Privacidade",
      AppStrings.showOnRankings: "Aparecer nos rankings",
      AppStrings.accountSectionTitle: "Conta",
      AppStrings.logoutButton: "Sair",
      AppStrings.logoutConfirmTitle: "Sair do Invest Game?",
      AppStrings.logoutConfirmMessage: "Tem certeza que deseja encerrar sua sessão?",
      AppStrings.cancelButton: "Cancelar",

      AppStrings.levelUpAchieved: "Nível {level} alcançado!",

      AppStrings.academyLevelLabel: "Investidor Nível {level}",
      AppStrings.academyXpEarnedLabel: "{xp} XP conquistados na Academia",
      AppStrings.academyContinueSectionLabel: "CONTINUAR",
      AppStrings.academyXpToCompleteLabel: "+{xp} XP ao concluir",
      AppStrings.academyStartLessonButton: "Começar Lição",
      AppStrings.academyModulesSectionLabel: "MÓDULOS",
      AppStrings.academyLessonsSectionLabel: "LIÇÕES",
      AppStrings.academyLessonsProgressLabel: "{completed} / {total} lições",
      AppStrings.academyLessonCompleteTitle: "Lição Concluída!",
      AppStrings.academyXpPill: "+{xp} XP",
      AppStrings.academyContinueButton: "Continuar",
      AppStrings.academyConcludeButton: "Concluir",
      AppStrings.academyBackToAcademyButton: "Voltar à Academia",
      AppStrings.academyModuleStatusCompleted: "MÓDULO CONCLUÍDO",
      AppStrings.academyModuleStatusInProgress: "EM ANDAMENTO",
      AppStrings.academyModuleStatusAvailable: "DISPONÍVEL",
      AppStrings.academyModuleStatusComingSoon: "EM BREVE",
      AppStrings.academyModuleStatusLocked: "BLOQUEADO",
      AppStrings.academySchoolsSectionLabel: "TRILHA",
      AppStrings.academyDomainsSectionLabel: "ESCOLAS",
      AppStrings.academyCatalogErrorTitle: "Não foi possível carregar a Academia",
      AppStrings.academyCatalogErrorBody: "Verifique sua conexão e tente novamente.",
      AppStrings.academyMasterySectionLabel: "SUA MAESTRIA",
      AppStrings.academyMasteryPercentLabel: "{percent}% concluído",
      AppStrings.academyKnowledgeLevelLabel: "Progresso de conhecimento: {tier}",
      AppStrings.academyMicroExerciseLabel: "EXERCÍCIO RÁPIDO",
      AppStrings.academyApplyLabel: "APLIQUE O QUE APRENDEU",
      AppStrings.academyCorrectFeedbackTitle: "Isso mesmo!",
      AppStrings.academyIncorrectFeedbackTitle: "Quase! Vamos entender:",

      AppStrings.academyProgressLabel: "Progresso",
      AppStrings.academyRealMasteryLabel: "Maestria",
      AppStrings.masteryTierExploring: "Explorando",
      AppStrings.masteryTierUnderstanding: "Entendendo",
      AppStrings.masteryTierApplying: "Aplicando",
      AppStrings.masteryTierMastering: "Dominando",

      AppStrings.academyRecommendedSectionLabel: "RECOMENDADO PARA VOCÊ",
      AppStrings.academyRecommendationContinueReason: "O próximo passo da sua jornada",
      AppStrings.academyRecommendationReviewReason: "Você errou uma pergunta aqui — vale revisar",
      AppStrings.academyReviewCardTitle: "Revisão de hoje",
      AppStrings.academyReviewCardSubtitle: "{count} lições · ~{minutes} min",
      AppStrings.academyReviewStartButton: "Começar revisão",
      AppStrings.academyReviewEmptyState: "Tudo em dia — nada para revisar agora.",

      AppStrings.financialLabSectionLabel: "LABORATÓRIO FINANCEIRO",
      AppStrings.financialLabTitle: "Laboratório Financeiro",
      AppStrings.financialLabSubtitle: "Simule cenários e veja os conceitos em ação.",
      AppStrings.compoundInterestLabTitle: "Juros Compostos",
      AppStrings.compoundInterestLabSubtitle: "Veja como aporte, prazo e taxa mudam o resultado.",
      AppStrings.labComingSoon: "Em breve",
      AppStrings.inflationLabTitle: "Inflação",
      AppStrings.fixedIncomeLabTitle: "Renda Fixa",
      AppStrings.diversificationLabTitle: "Diversificação",
      AppStrings.portfolioLabTitle: "Carteira",
      AppStrings.labInitialAmountLabel: "Valor inicial",
      AppStrings.labMonthlyContributionLabel: "Aporte mensal",
      AppStrings.labAnnualReturnLabel: "Retorno anual",
      AppStrings.labYearsLabel: "Anos",
      AppStrings.labFinalValueLabel: "Valor final",
      AppStrings.labTotalContributionsLabel: "Total investido",
      AppStrings.labTotalGrowthLabel: "Total em rendimentos",
      AppStrings.labExplanationIncreaseYears:
          "Aumentar o prazo de {from} para {to} anos ampliou bastante o efeito dos juros compostos sobre o resultado.",
      AppStrings.labExplanationDecreaseYears:
          "Reduzir o prazo de {from} para {to} anos deu menos tempo para os juros compostos atuarem.",
      AppStrings.labExplanationIncreaseReturn:
          "Aumentar o retorno anual de {from}% para {to}% acelerou o crescimento do seu dinheiro ao longo do tempo.",
      AppStrings.labExplanationDecreaseReturn:
          "Reduzir o retorno anual de {from}% para {to}% desacelerou o crescimento do seu dinheiro ao longo do tempo.",
      AppStrings.labExplanationInitial: "Ajuste os valores para ver como cada variável muda o resultado final.",
      AppStrings.labYearTooltipLabel: "Ano {year}",

      AppStrings.appBarPlayerNamedGreeting: "{petName} · Nível {level}",
      AppStrings.appBarPlayerGenericGreeting: "Nível {level} · Explorador",
      AppStrings.profileTooltip: "Perfil",
      AppStrings.notificationsTooltip: "Notificações",
      AppStrings.logoutTooltip: "Sair",
      AppStrings.navHome: "Início",
      AppStrings.navWallet: "Carteira",
      AppStrings.navPassiveIncome: "Proventos",
      AppStrings.navAcademy: "Academia",
      AppStrings.navMentor: "Mentor",
      AppStrings.homeContinueLearningEyebrow: "Missão de hoje",
      AppStrings.homeContinueLearningCta: "Continuar Aprendendo",
      AppStrings.homeAllLessonsCompleteTitle: "Você concluiu tudo por aqui!",
      AppStrings.homeAllLessonsCompleteBody: "Novos módulos chegam em breve. Explore a Academia para revisar o que já aprendeu.",
      AppStrings.homeExploreAcademyCta: "Ver Academia",
      AppStrings.homeLevelProgressLabel: "XP para o próximo nível",
      AppStrings.homeNextEvolutionLabel: "XP para a próxima evolução",
      AppStrings.homeMaxEvolutionLabel: "Evolução máxima alcançada",
      AppStrings.homeKnowledgeMapLabel: "SUA TRILHA DE CONHECIMENTO",
      AppStrings.homeViewFullAcademyCta: "Ver trilha completa",
      AppStrings.homePortfolioBridgeLabel: "SUA CARTEIRA",
      AppStrings.homePortfolioBridgeApplyMessage: "Você já concluiu {count} lições — veja como aplicar esse conhecimento na sua carteira real.",
      AppStrings.homeViewPortfolioCta: "Ver Carteira",
      AppStrings.homeAnswerInvestorProfileLink: "Ainda não respondeu seu perfil de investidor? Responder agora",
      AppStrings.levelTierBeginner: "Iniciante",
      AppStrings.levelTierLearner: "Aprendiz",
      AppStrings.levelTierExplorer: "Explorador",
      AppStrings.levelTierInvestor: "Investidor",
      AppStrings.levelTierAnalyst: "Analista",
      AppStrings.levelTierStrategist: "Estrategista",
      AppStrings.levelTierSpecialist: "Especialista",

      // Knowledge Progress tiers (curriculum completion, not XP)
      AppStrings.knowledgeLevelAbsoluteBeginner: "Iniciante Absoluto",
      AppStrings.knowledgeLevelFinancialApprentice: "Aprendiz Financeiro",
      AppStrings.knowledgeLevelFinancialOrganizer: "Organizador Financeiro",
      AppStrings.knowledgeLevelFinancialProtector: "Protetor Financeiro",
      AppStrings.knowledgeLevelBeginnerInvestor: "Investidor Iniciante",
      AppStrings.knowledgeLevelInvestor: "Investidor",
      AppStrings.knowledgeLevelAnalyst: "Analista",
      AppStrings.knowledgeLevelWealthBuilder: "Construtor de Patrimônio",
      AppStrings.knowledgeLevelFinancialStrategist: "Estrategista Financeiro",
      AppStrings.knowledgeLevelFinancialMaster: "Mestre Financeiro",

      AppStrings.companionHeaderTooltip: "Abrir seu companheiro",
      AppStrings.companionDismissTooltip: "Fechar",
      AppStrings.companionInteractionTitle: "Como posso ajudar?",
      AppStrings.companionInteractionSubtitle: "Escolha para onde ir",
      AppStrings.companionInteractionLearn: "Aprender",
      AppStrings.companionInteractionPortfolio: "Carteira",
      AppStrings.companionInteractionProgress: "Progresso",
      AppStrings.companionActionContinue: "Continuar",
      AppStrings.companionActionViewPortfolio: "Ver Carteira",
      AppStrings.companionActionViewProgress: "Ver Progresso",
      AppStrings.companionHomeXpToNextLevel: "Faltam {xp} XP para o próximo nível!",
      AppStrings.companionAcademyContinueLesson: "Você estava progredindo em \"{lessonTitle}\". Continuar de onde parou?",
      AppStrings.companionAcademyReviewDue: "Você tem {count} conceitos para revisar. Vamos reforçar o que já aprendeu?",
      AppStrings.companionPortfolioDiversified: "Sua carteira está distribuída em {count} ativos diferentes.",
      AppStrings.companionMentorNudge: "Tem alguma dúvida sobre investimentos? Pergunte para mim.",
      AppStrings.companionProfileSummary: "Você está no nível {level} — {stage}.",
      AppStrings.companionEventLessonCompleted: "Muito bem! Você concluiu a lição.",
      AppStrings.companionEventXpGained: "+{xp} XP! Continue assim.",
      AppStrings.companionEventLevelUp: "Nível {level} alcançado! Estou orgulhoso de você.",
      AppStrings.companionEventAchievementUnlocked: "Conquista desbloqueada: {title}!",
      AppStrings.companionEventEvolved: "Eu evoluí! Agora sou {stage}.",
      AppStrings.companionEventDifficultyDetected: "Notei que você errou algumas em {school}. Que tal revisar juntos?",
      AppStrings.companionEventSchoolMastered: "Você concluiu tudo disponível em {school}! Muito bem!",

      AppStrings.forgotPasswordTitle: "Recuperar senha",
      AppStrings.forgotPasswordSubtitle: "Digite seu e-mail e enviaremos um link para redefinir sua senha.",
      AppStrings.forgotPasswordEmailHint: "Seu e-mail",
      AppStrings.forgotPasswordSendButton: "Enviar link",
      AppStrings.forgotPasswordConfirmationMessage: "Se existir uma conta com esse e-mail, você receberá instruções em instantes.",
      AppStrings.forgotPasswordHaveCodeLink: "Já tenho um código de redefinição",
      AppStrings.resetPasswordTitle: "Redefinir senha",
      AppStrings.resetPasswordSubtitle: "Cole o código que enviamos por e-mail e escolha uma nova senha.",
      AppStrings.resetPasswordTokenHint: "Código de redefinição",
      AppStrings.resetPasswordNewPasswordHint: "Nova senha",
      AppStrings.resetPasswordSubmitButton: "Redefinir senha",
      AppStrings.resetPasswordSuccessMessage: "Senha redefinida com sucesso! Faça login com sua nova senha.",
      AppStrings.resetPasswordMismatchError: "As senhas não coincidem.",
      AppStrings.resetPasswordFieldsRequiredError: "Preencha todos os campos.",

      AppStrings.wealthLegendPatrimony: "Patrimônio",
      AppStrings.wealthLegendInvested: "Investido",
      AppStrings.wealthLegendAppliedValue: "Valor aplicado",
      AppStrings.wealthLegendCapitalGain: "Ganho de Capital",
      AppStrings.proventosLegendReceived: "Recebidos",
      AppStrings.proventosLegendExpected: "A receber",
      AppStrings.noAssetsRegisteredYet: "Nenhum ativo registrado ainda.",
      AppStrings.retryButtonLabel: "Tentar novamente",
      AppStrings.mentorNewChatTooltip: "Nova conversa",
      AppStrings.mentorHistoryTooltip: "Histórico",
      AppStrings.mentorConversationHistoryTitle: "Conversas",
      AppStrings.mentorNoConversationsTitle: "Nenhuma conversa ainda",
      AppStrings.mentorNoConversationsSubtitle: "Suas conversas com o mentor vão aparecer aqui.",
      AppStrings.mentorConversationsLoadError: "Não foi possível carregar suas conversas.",
      AppStrings.mentorRenameConversationTitle: "Renomear conversa",
      AppStrings.mentorRenameConversationHint: "Título da conversa",
      AppStrings.mentorRenameConversationSave: "Salvar",
      AppStrings.mentorDeleteConversationTitle: "Apagar conversa?",
      AppStrings.mentorDeleteConversationConfirm: "Esta conversa e todas as mensagens serão apagadas permanentemente.",
      AppStrings.mentorDeleteConversationButton: "Apagar",
      AppStrings.initialPortfolioTitle: "Portfólio Inicial",
      AppStrings.portfolioCardTitle: "Portfólio",
      AppStrings.profileTitle: "Perfil",
      AppStrings.petTeacherAskMentor: "Pergunte ao mentor:",
      AppStrings.petTeacherOwnedGreeting: "Vamos entender melhor {assetName}!",
      AppStrings.petTeacherNotOwnedGreeting: "Quer saber mais sobre {assetName}?",
    },
    'en': {
      AppStrings.welcomeBack: "Welcome back",
      AppStrings.loginToContinue: "Login to continue",
      AppStrings.emailOrUserHint: "Email or Username",
      AppStrings.passwordHint: "Password",
      AppStrings.forgotPassword: "Forgot password?",
      AppStrings.noAccountSignUp: "Don't have an account? Sign up",
      AppStrings.loginButton: "Login",
      AppStrings.createAccount: "Create Account",
      AppStrings.fillDetails: "Fill in your details",
      AppStrings.nameHint: "Full Name",
      AppStrings.confirmPasswordHint: "Confirm Password",
      AppStrings.signupButton: "Sign Up",
      AppStrings.alreadyHaveAccount: "Already have an account? Login",

      AppStrings.pleaseAnswerAllQuestions: "Please answer all questions",
      AppStrings.onboardingFailed: "Failed to submit answers",
      AppStrings.noQuestionsAvailable: "No questions available.",
      AppStrings.failedToLoadQuestions: "Failed to load questions",

      AppStrings.petProfileTitle: "Pet Profile",
      AppStrings.failedToSavePet: "Failed to save pet",

      AppStrings.meetPetTitle: "Meet Your Companion",
      AppStrings.meetPetGreeting: "Hello!",
      AppStrings.meetPetIntro: "I'm your financial companion. I'll help you learn about investing, stay disciplined and celebrate every achievement along your journey.",
      AppStrings.meetPetNeedName: "But first... I need a name!",
      AppStrings.meetPetSpeciesPrompt: "Choose your companion's species",
      AppStrings.meetPetContinue: "Let's get started!",
      AppStrings.meetPetPreviewTitle: "What we'll do together",
      AppStrings.meetPetPreviewCelebrate: "Celebrate every milestone of your journey",
      AppStrings.meetPetPreviewLearn: "Learn about investing at your own pace",
      AppStrings.meetPetPreviewRemember: "Remember the important moments of our journey",

      AppStrings.namePetTitle: "Name Your Pet",
      AppStrings.namePetPrompt: "What would you like to call your companion?",
      AppStrings.namePetHint: "Companion's name",
      AppStrings.namePetContinue: "Continue",
      AppStrings.namePetReaction: "I love my new name! Let's start your journey!",
      AppStrings.namePetRequiredError: "Choose a name to continue",

      AppStrings.financialGoalTitle: "What will be your first mission?",
      AppStrings.financialGoalSubtitle: "Choose what you want to achieve. You can change it later.",
      AppStrings.financialGoalContinue: "Continue",

      AppStrings.onboardingSkip: "Skip",
      AppStrings.onboardingNext: "Next",

      AppStrings.welcomeHeadline: "Your financial journey starts here.",
      AppStrings.welcomeSubheadline: "Learn. Invest. Evolve.",
      AppStrings.welcomeBody: "Turn financial knowledge into real progress.",
      AppStrings.welcomeCta: "Start",

      AppStrings.academyIntroTitle: "Learn at your own pace.",
      AppStrings.academyIntroSubtitle: "Knowledge before investing.",
      AppStrings.academyIntroBody: "Short lessons, challenges, and quizzes designed to help you actually understand investing.",
      AppStrings.academyIntroXpBadge: "+{xp} XP per completed lesson",

      AppStrings.gamificationIntroTitle: "Learn. Play. Evolve.",
      AppStrings.gamificationIntroSubtitle: "Turn knowledge into progress.",
      AppStrings.onboardingLevelBadge: "Level {level}",

      AppStrings.missionCompleteLabel: "Mission Complete",
      AppStrings.missionCompoundInterestTitle: "Learn about compound interest",

      AppStrings.timeHorizonTitle: "When do you want to achieve it?",
      AppStrings.timeHorizonSubtitle: "This paces your journey — you can change it later.",

      AppStrings.journeyReadyTitle: "Your journey is ready.",
      AppStrings.journeyReadySubtitle: "Now it's time to start evolving.",
      AppStrings.journeyReadyGoalLabel: "Your goal",
      AppStrings.journeyReadyPathLabel: "Your path",
      AppStrings.journeyReadyPathValue: "Learn to Invest",
      AppStrings.journeyReadyCompanionLabel: "Your companion",
      AppStrings.journeyReadyProgressLabel: "Your progress",
      AppStrings.journeyReadyFirstMissionLabel: "Your first mission",
      AppStrings.journeyReadyCta: "Start My Journey",

      AppStrings.portfolioChoiceTitle: "Would you like to connect your investments now?",
      AppStrings.portfolioChoiceBody: "You can import your portfolio automatically, add investments manually, or skip for now. You can always do this later.",
      AppStrings.portfolioChoiceFootnote: "There's no rush — {petName} will be here when you're ready.",
      AppStrings.importPortfolioButton: "Import Portfolio",
      AppStrings.addManuallyButton: "Add Manually",
      AppStrings.skipForNowButton: "Skip For Now",
      AppStrings.importComingSoonTitle: "Coming soon",
      AppStrings.importComingSoonBody: "Automatic import (B3, brokers, CSV) is still being built. For now, you can add your assets manually or skip this step.",
      AppStrings.okButton: "Got it",

      AppStrings.portfolioNotConnectedTitle: "Portfolio not connected yet",
      AppStrings.portfolioNotConnectedBody: "Connect your investments whenever you're ready — no rush.",
      AppStrings.connectInvestmentsButton: "Connect Investments",
      AppStrings.suggestedActionsTitle: "What to do now",
      AppStrings.suggestedActionCompleteLesson: "Complete your first lesson",
      AppStrings.suggestedActionTodayMission: "Complete today's mission",
      AppStrings.suggestedActionLearnDividends: "Learn about dividends",
      AppStrings.suggestedActionFirstQuiz: "Start your first quiz",
      AppStrings.suggestedActionInvestorProfile: "Complete your investor profile",
      AppStrings.comingSoonSnack: "Coming soon!",

      AppStrings.portfolioReminderMessage: "I noticed we still haven't connected your investments. When you're ready, I can analyze your portfolio and create personalized missions. There is no rush.",
      AppStrings.portfolioReminderCta: "Connect now",
      AppStrings.portfolioReminderDismiss: "Not now",

      AppStrings.companionSectionTitle: "Companion",
      AppStrings.renamePetLabel: "Companion's name",
      AppStrings.renamePetButton: "Rename",
      AppStrings.renamePetDialogTitle: "Rename companion",
      AppStrings.renamePetSuccess: "Name updated!",

      AppStrings.settingsTitle: "Settings",
      AppStrings.settingsSubtitle: "Personalize your experience, Commander.",
      AppStrings.languageSectionTitle: "Language",
      AppStrings.languagePt: "Português (Brasil)",
      AppStrings.languageEn: "English",
      AppStrings.languageEs: "Español",
      AppStrings.languageUpdated: "Language updated",
      AppStrings.appearanceSectionTitle: "Appearance",
      AppStrings.appearanceLightLabel: "Light",
      AppStrings.appearanceLightDescription: "Bright, clean and friendly",
      AppStrings.appearanceDarkLabel: "Dark",
      AppStrings.appearanceDarkDescription: "Premium, immersive and futuristic",
      AppStrings.appearanceSystemLabel: "System",
      AppStrings.appearanceSystemDescription: "Follows your device settings",
      AppStrings.appearanceUpdated: "Appearance updated",
      AppStrings.notificationsSectionTitle: "Notifications",
      AppStrings.dailyMissionReminders: "Daily mission reminders",
      AppStrings.achievementAlerts: "Achievement alerts",
      AppStrings.privacySectionTitle: "Privacy",
      AppStrings.showOnRankings: "Show up on rankings",
      AppStrings.accountSectionTitle: "Account",
      AppStrings.logoutButton: "Logout",
      AppStrings.logoutConfirmTitle: "Leave Invest Game?",
      AppStrings.logoutConfirmMessage: "Are you sure you want to end your session?",
      AppStrings.cancelButton: "Cancel",

      AppStrings.levelUpAchieved: "Level {level} reached!",

      AppStrings.academyLevelLabel: "Investor Level {level}",
      AppStrings.academyXpEarnedLabel: "{xp} XP earned in the Academy",
      AppStrings.academyContinueSectionLabel: "CONTINUE",
      AppStrings.academyXpToCompleteLabel: "+{xp} XP on completion",
      AppStrings.academyStartLessonButton: "Start Lesson",
      AppStrings.academyModulesSectionLabel: "MODULES",
      AppStrings.academyLessonsSectionLabel: "LESSONS",
      AppStrings.academyLessonsProgressLabel: "{completed} / {total} lessons",
      AppStrings.academyLessonCompleteTitle: "Lesson Complete!",
      AppStrings.academyXpPill: "+{xp} XP",
      AppStrings.academyContinueButton: "Continue",
      AppStrings.academyConcludeButton: "Finish",
      AppStrings.academyBackToAcademyButton: "Back to Academy",
      AppStrings.academyModuleStatusCompleted: "MODULE COMPLETED",
      AppStrings.academyModuleStatusInProgress: "IN PROGRESS",
      AppStrings.academyModuleStatusAvailable: "AVAILABLE",
      AppStrings.academyModuleStatusComingSoon: "COMING SOON",
      AppStrings.academyModuleStatusLocked: "LOCKED",
      AppStrings.academySchoolsSectionLabel: "JOURNEY",
      AppStrings.academyDomainsSectionLabel: "SCHOOLS",
      AppStrings.academyCatalogErrorTitle: "Couldn't load the Academy",
      AppStrings.academyCatalogErrorBody: "Check your connection and try again.",
      AppStrings.academyMasterySectionLabel: "YOUR MASTERY",
      AppStrings.academyMasteryPercentLabel: "{percent}% complete",
      AppStrings.academyKnowledgeLevelLabel: "Knowledge progress: {tier}",
      AppStrings.academyMicroExerciseLabel: "QUICK EXERCISE",
      AppStrings.academyApplyLabel: "APPLY WHAT YOU LEARNED",
      AppStrings.academyCorrectFeedbackTitle: "That's right!",
      AppStrings.academyIncorrectFeedbackTitle: "Almost! Let's understand:",

      AppStrings.academyProgressLabel: "Progress",
      AppStrings.academyRealMasteryLabel: "Mastery",
      AppStrings.masteryTierExploring: "Exploring",
      AppStrings.masteryTierUnderstanding: "Understanding",
      AppStrings.masteryTierApplying: "Applying",
      AppStrings.masteryTierMastering: "Mastering",

      AppStrings.academyRecommendedSectionLabel: "RECOMMENDED FOR YOU",
      AppStrings.academyRecommendationContinueReason: "The next step in your journey",
      AppStrings.academyRecommendationReviewReason: "You missed a question here — worth a review",
      AppStrings.academyReviewCardTitle: "Today's Review",
      AppStrings.academyReviewCardSubtitle: "{count} lessons · ~{minutes} min",
      AppStrings.academyReviewStartButton: "Start Review",
      AppStrings.academyReviewEmptyState: "You're all caught up — nothing to review right now.",

      AppStrings.financialLabSectionLabel: "FINANCIAL LAB",
      AppStrings.financialLabTitle: "Financial Lab",
      AppStrings.financialLabSubtitle: "Simulate scenarios and see the concepts in action.",
      AppStrings.compoundInterestLabTitle: "Compound Interest",
      AppStrings.compoundInterestLabSubtitle: "See how contributions, time and rate change the outcome.",
      AppStrings.labComingSoon: "Coming soon",
      AppStrings.inflationLabTitle: "Inflation",
      AppStrings.fixedIncomeLabTitle: "Fixed Income",
      AppStrings.diversificationLabTitle: "Diversification",
      AppStrings.portfolioLabTitle: "Portfolio",
      AppStrings.labInitialAmountLabel: "Initial amount",
      AppStrings.labMonthlyContributionLabel: "Monthly contribution",
      AppStrings.labAnnualReturnLabel: "Annual return",
      AppStrings.labYearsLabel: "Years",
      AppStrings.labFinalValueLabel: "Final value",
      AppStrings.labTotalContributionsLabel: "Total contributed",
      AppStrings.labTotalGrowthLabel: "Total growth",
      AppStrings.labExplanationIncreaseYears:
          "Increasing the time horizon from {from} to {to} years dramatically increased the impact of compound growth.",
      AppStrings.labExplanationDecreaseYears:
          "Reducing the time horizon from {from} to {to} years left less time for compound growth to work.",
      AppStrings.labExplanationIncreaseReturn:
          "Increasing the annual return from {from}% to {to}% sped up how fast your money grows over time.",
      AppStrings.labExplanationDecreaseReturn:
          "Reducing the annual return from {from}% to {to}% slowed down how fast your money grows over time.",
      AppStrings.labExplanationInitial: "Adjust the values to see how each variable changes the final result.",
      AppStrings.labYearTooltipLabel: "Year {year}",

      AppStrings.appBarPlayerNamedGreeting: "{petName} · Level {level}",
      AppStrings.appBarPlayerGenericGreeting: "Level {level} · Explorer",
      AppStrings.profileTooltip: "Profile",
      AppStrings.notificationsTooltip: "Notifications",
      AppStrings.logoutTooltip: "Logout",
      AppStrings.navHome: "Home",
      AppStrings.navWallet: "Wallet",
      AppStrings.navPassiveIncome: "Income",
      AppStrings.navAcademy: "Academy",
      AppStrings.navMentor: "Mentor",
      AppStrings.homeContinueLearningEyebrow: "Today's mission",
      AppStrings.homeContinueLearningCta: "Continue Learning",
      AppStrings.homeAllLessonsCompleteTitle: "You've completed everything here!",
      AppStrings.homeAllLessonsCompleteBody: "New modules are coming soon. Explore the Academy to review what you've learned.",
      AppStrings.homeExploreAcademyCta: "View Academy",
      AppStrings.homeLevelProgressLabel: "XP to next level",
      AppStrings.homeNextEvolutionLabel: "XP to next evolution",
      AppStrings.homeMaxEvolutionLabel: "Maximum evolution reached",
      AppStrings.homeKnowledgeMapLabel: "YOUR KNOWLEDGE MAP",
      AppStrings.homeViewFullAcademyCta: "View full path",
      AppStrings.homePortfolioBridgeLabel: "YOUR PORTFOLIO",
      AppStrings.homePortfolioBridgeApplyMessage: "You've completed {count} lessons — see how to apply that knowledge to your real portfolio.",
      AppStrings.homeViewPortfolioCta: "View Portfolio",
      AppStrings.homeAnswerInvestorProfileLink: "Haven't answered your investor profile yet? Answer now",
      AppStrings.levelTierBeginner: "Beginner",
      AppStrings.levelTierLearner: "Learner",
      AppStrings.levelTierExplorer: "Explorer",
      AppStrings.levelTierInvestor: "Investor",
      AppStrings.levelTierAnalyst: "Analyst",
      AppStrings.levelTierStrategist: "Strategist",
      AppStrings.levelTierSpecialist: "Specialist",

      // Knowledge Progress tiers (curriculum completion, not XP)
      AppStrings.knowledgeLevelAbsoluteBeginner: "Absolute Beginner",
      AppStrings.knowledgeLevelFinancialApprentice: "Financial Apprentice",
      AppStrings.knowledgeLevelFinancialOrganizer: "Financial Organizer",
      AppStrings.knowledgeLevelFinancialProtector: "Financial Protector",
      AppStrings.knowledgeLevelBeginnerInvestor: "Beginner Investor",
      AppStrings.knowledgeLevelInvestor: "Investor",
      AppStrings.knowledgeLevelAnalyst: "Analyst",
      AppStrings.knowledgeLevelWealthBuilder: "Wealth Builder",
      AppStrings.knowledgeLevelFinancialStrategist: "Financial Strategist",
      AppStrings.knowledgeLevelFinancialMaster: "Financial Master",

      AppStrings.companionHeaderTooltip: "Open your companion",
      AppStrings.companionDismissTooltip: "Dismiss",
      AppStrings.companionInteractionTitle: "How can I help?",
      AppStrings.companionInteractionSubtitle: "Choose where to go",
      AppStrings.companionInteractionLearn: "Learn",
      AppStrings.companionInteractionPortfolio: "Portfolio",
      AppStrings.companionInteractionProgress: "Progress",
      AppStrings.companionActionContinue: "Continue",
      AppStrings.companionActionViewPortfolio: "View Portfolio",
      AppStrings.companionActionViewProgress: "View Progress",
      AppStrings.companionHomeXpToNextLevel: "Only {xp} XP to your next level!",
      AppStrings.companionAcademyContinueLesson: "You were making progress on \"{lessonTitle}\". Continue where you left off?",
      AppStrings.companionAcademyReviewDue: "You have {count} concepts to review. Let's reinforce what you've learned?",
      AppStrings.companionPortfolioDiversified: "Your portfolio is spread across {count} different assets.",
      AppStrings.companionMentorNudge: "Have a question about investing? Ask me anything.",
      AppStrings.companionProfileSummary: "You're at level {level} — {stage}.",
      AppStrings.companionEventLessonCompleted: "Great job! You completed the lesson.",
      AppStrings.companionEventXpGained: "+{xp} XP! Keep it up.",
      AppStrings.companionEventLevelUp: "Level {level} reached! I'm proud of you.",
      AppStrings.companionEventAchievementUnlocked: "Achievement unlocked: {title}!",
      AppStrings.companionEventEvolved: "I evolved! I'm now {stage}.",
      AppStrings.companionEventDifficultyDetected: "I noticed a few misses in {school}. Want to review it together?",
      AppStrings.companionEventSchoolMastered: "You finished everything available in {school}! Well done!",

      AppStrings.forgotPasswordTitle: "Recover password",
      AppStrings.forgotPasswordSubtitle: "Enter your email and we'll send you a link to reset your password.",
      AppStrings.forgotPasswordEmailHint: "Your email",
      AppStrings.forgotPasswordSendButton: "Send link",
      AppStrings.forgotPasswordConfirmationMessage: "If an account exists for that email, you'll receive instructions shortly.",
      AppStrings.forgotPasswordHaveCodeLink: "I already have a reset code",
      AppStrings.resetPasswordTitle: "Reset password",
      AppStrings.resetPasswordSubtitle: "Paste the code we emailed you and choose a new password.",
      AppStrings.resetPasswordTokenHint: "Reset code",
      AppStrings.resetPasswordNewPasswordHint: "New password",
      AppStrings.resetPasswordSubmitButton: "Reset password",
      AppStrings.resetPasswordSuccessMessage: "Password reset successfully! Log in with your new password.",
      AppStrings.resetPasswordMismatchError: "Passwords don't match.",
      AppStrings.resetPasswordFieldsRequiredError: "Please fill in all fields.",

      AppStrings.wealthLegendPatrimony: "Net worth",
      AppStrings.wealthLegendInvested: "Invested",
      AppStrings.wealthLegendAppliedValue: "Amount invested",
      AppStrings.wealthLegendCapitalGain: "Capital gain",
      AppStrings.proventosLegendReceived: "Received",
      AppStrings.proventosLegendExpected: "Expected",
      AppStrings.noAssetsRegisteredYet: "No assets registered yet.",
      AppStrings.retryButtonLabel: "Try again",
      AppStrings.mentorNewChatTooltip: "New chat",
      AppStrings.mentorHistoryTooltip: "History",
      AppStrings.mentorConversationHistoryTitle: "Conversations",
      AppStrings.mentorNoConversationsTitle: "No conversations yet",
      AppStrings.mentorNoConversationsSubtitle: "Your conversations with the mentor will show up here.",
      AppStrings.mentorConversationsLoadError: "We couldn't load your conversations.",
      AppStrings.mentorRenameConversationTitle: "Rename conversation",
      AppStrings.mentorRenameConversationHint: "Conversation title",
      AppStrings.mentorRenameConversationSave: "Save",
      AppStrings.mentorDeleteConversationTitle: "Delete conversation?",
      AppStrings.mentorDeleteConversationConfirm: "This conversation and all its messages will be permanently deleted.",
      AppStrings.mentorDeleteConversationButton: "Delete",
      AppStrings.initialPortfolioTitle: "Starting Portfolio",
      AppStrings.portfolioCardTitle: "Portfolio",
      AppStrings.profileTitle: "Profile",
      AppStrings.petTeacherAskMentor: "Ask the mentor:",
      AppStrings.petTeacherOwnedGreeting: "Let's understand {assetName} better!",
      AppStrings.petTeacherNotOwnedGreeting: "Want to know more about {assetName}?",
    },
    'es': {
      AppStrings.welcomeBack: "Bienvenido de nuevo",
      AppStrings.loginToContinue: "Inicia sesión para continuar",
      AppStrings.emailOrUserHint: "Correo o Usuario",
      AppStrings.passwordHint: "Contraseña",
      AppStrings.forgotPassword: "¿Olvidaste tu contraseña?",
      AppStrings.noAccountSignUp: "¿No tienes cuenta? Regístrate",
      AppStrings.loginButton: "Entrar",
      AppStrings.createAccount: "Crear Cuenta",
      AppStrings.fillDetails: "Completa tus datos",
      AppStrings.nameHint: "Nombre Completo",
      AppStrings.confirmPasswordHint: "Confirmar Contraseña",
      AppStrings.signupButton: "Registrarse",
      AppStrings.alreadyHaveAccount: "¿Ya tienes cuenta? Entrar",

      AppStrings.pleaseAnswerAllQuestions: "Responde todas las preguntas",
      AppStrings.onboardingFailed: "Error al enviar las respuestas",
      AppStrings.noQuestionsAvailable: "No hay preguntas disponibles.",
      AppStrings.failedToLoadQuestions: "Error al cargar las preguntas",

      AppStrings.petProfileTitle: "Perfil de la Mascota",
      AppStrings.failedToSavePet: "Error al guardar la mascota",

      AppStrings.meetPetTitle: "Conoce a tu Compañero",
      AppStrings.meetPetGreeting: "¡Hola!",
      AppStrings.meetPetIntro: "Soy tu compañero financiero. Te ayudaré a aprender sobre inversiones, mantener la disciplina y celebrar cada logro en tu camino.",
      AppStrings.meetPetNeedName: "Pero antes... ¡necesito un nombre!",
      AppStrings.meetPetSpeciesPrompt: "Elige la especie de tu compañero",
      AppStrings.meetPetContinue: "¡Vamos a empezar!",
      AppStrings.meetPetPreviewTitle: "Lo que haremos juntos",
      AppStrings.meetPetPreviewCelebrate: "Celebrar cada logro de tu viaje",
      AppStrings.meetPetPreviewLearn: "Aprender sobre inversiones a tu ritmo",
      AppStrings.meetPetPreviewRemember: "Recordar los momentos importantes de nuestro viaje",

      AppStrings.namePetTitle: "Nombra a tu Mascota",
      AppStrings.namePetPrompt: "¿Cómo te gustaría llamar a tu compañero?",
      AppStrings.namePetHint: "Nombre del compañero",
      AppStrings.namePetContinue: "Continuar",
      AppStrings.namePetReaction: "¡Me encanta mi nuevo nombre! ¡Comencemos tu viaje!",
      AppStrings.namePetRequiredError: "Elige un nombre para continuar",

      AppStrings.financialGoalTitle: "¿Cuál será tu primera misión?",
      AppStrings.financialGoalSubtitle: "Elige lo que quieres lograr. Puedes cambiarlo después.",
      AppStrings.financialGoalContinue: "Continuar",

      AppStrings.onboardingSkip: "Omitir",
      AppStrings.onboardingNext: "Siguiente",

      AppStrings.welcomeHeadline: "Tu viaje financiero comienza aquí.",
      AppStrings.welcomeSubheadline: "Aprende. Invierte. Evoluciona.",
      AppStrings.welcomeBody: "Convierte el conocimiento financiero en progreso real.",
      AppStrings.welcomeCta: "Comenzar",

      AppStrings.academyIntroTitle: "Aprende a tu ritmo.",
      AppStrings.academyIntroSubtitle: "Conocimiento antes de invertir.",
      AppStrings.academyIntroBody: "Lecciones cortas, desafíos y quizzes para que realmente entiendas de inversiones.",
      AppStrings.academyIntroXpBadge: "+{xp} XP por lección completada",

      AppStrings.gamificationIntroTitle: "Aprende. Juega. Evoluciona.",
      AppStrings.gamificationIntroSubtitle: "Convierte el conocimiento en progreso.",
      AppStrings.onboardingLevelBadge: "Nivel {level}",

      AppStrings.missionCompleteLabel: "Misión Completada",
      AppStrings.missionCompoundInterestTitle: "Aprende sobre el interés compuesto",

      AppStrings.timeHorizonTitle: "¿Cuándo quieres lograrlo?",
      AppStrings.timeHorizonSubtitle: "Esto marca el ritmo de tu viaje — puedes cambiarlo después.",

      AppStrings.journeyReadyTitle: "Tu viaje está listo.",
      AppStrings.journeyReadySubtitle: "Ahora es momento de empezar a evolucionar.",
      AppStrings.journeyReadyGoalLabel: "Tu objetivo",
      AppStrings.journeyReadyPathLabel: "Tu camino",
      AppStrings.journeyReadyPathValue: "Aprender a Invertir",
      AppStrings.journeyReadyCompanionLabel: "Tu compañero",
      AppStrings.journeyReadyProgressLabel: "Tu progreso",
      AppStrings.journeyReadyFirstMissionLabel: "Tu primera misión",
      AppStrings.journeyReadyCta: "Iniciar Mi Viaje",

      AppStrings.portfolioChoiceTitle: "¿Quieres conectar tus inversiones ahora?",
      AppStrings.portfolioChoiceBody: "Puedes importar tu portafolio automáticamente, agregar inversiones manualmente, o omitir por ahora. Siempre puedes hacerlo después.",
      AppStrings.portfolioChoiceFootnote: "No hay prisa — {petName} estará aquí cuando estés listo.",
      AppStrings.importPortfolioButton: "Importar Portafolio",
      AppStrings.addManuallyButton: "Agregar Manualmente",
      AppStrings.skipForNowButton: "Omitir por Ahora",
      AppStrings.importComingSoonTitle: "Próximamente",
      AppStrings.importComingSoonBody: "La importación automática (B3, corredoras, CSV) todavía se está construyendo. Por ahora, puedes agregar tus activos manualmente u omitir este paso.",
      AppStrings.okButton: "Entendido",

      AppStrings.portfolioNotConnectedTitle: "Portafolio aún no conectado",
      AppStrings.portfolioNotConnectedBody: "Conecta tus inversiones cuando estés listo — no hay prisa.",
      AppStrings.connectInvestmentsButton: "Conectar Inversiones",
      AppStrings.suggestedActionsTitle: "Qué hacer ahora",
      AppStrings.suggestedActionCompleteLesson: "Completar tu primera lección",
      AppStrings.suggestedActionTodayMission: "Completar la misión de hoy",
      AppStrings.suggestedActionLearnDividends: "Aprender sobre dividendos",
      AppStrings.suggestedActionFirstQuiz: "Hacer tu primer quiz",
      AppStrings.suggestedActionInvestorProfile: "Completar tu perfil de inversionista",
      AppStrings.comingSoonSnack: "¡Próximamente!",

      AppStrings.portfolioReminderMessage: "Noté que todavía no hemos conectado tus inversiones. Cuando estés listo, puedo analizar tu portafolio y crear misiones personalizadas. No hay prisa.",
      AppStrings.portfolioReminderCta: "Conectar ahora",
      AppStrings.portfolioReminderDismiss: "Ahora no",

      AppStrings.companionSectionTitle: "Compañero",
      AppStrings.renamePetLabel: "Nombre del compañero",
      AppStrings.renamePetButton: "Renombrar",
      AppStrings.renamePetDialogTitle: "Renombrar compañero",
      AppStrings.renamePetSuccess: "¡Nombre actualizado!",

      AppStrings.settingsTitle: "Configuración",
      AppStrings.settingsSubtitle: "Personaliza tu experiencia, Comandante.",
      AppStrings.languageSectionTitle: "Idioma",
      AppStrings.languagePt: "Português (Brasil)",
      AppStrings.languageEn: "English",
      AppStrings.languageEs: "Español",
      AppStrings.languageUpdated: "Idioma actualizado",
      AppStrings.appearanceSectionTitle: "Apariencia",
      AppStrings.appearanceLightLabel: "Claro",
      AppStrings.appearanceLightDescription: "Brillante, limpio y acogedor",
      AppStrings.appearanceDarkLabel: "Oscuro",
      AppStrings.appearanceDarkDescription: "Premium, inmersivo y futurista",
      AppStrings.appearanceSystemLabel: "Sistema",
      AppStrings.appearanceSystemDescription: "Sigue la configuración de tu dispositivo",
      AppStrings.appearanceUpdated: "Apariencia actualizada",
      AppStrings.notificationsSectionTitle: "Notificaciones",
      AppStrings.dailyMissionReminders: "Recordatorios de misiones diarias",
      AppStrings.achievementAlerts: "Alertas de logros",
      AppStrings.privacySectionTitle: "Privacidad",
      AppStrings.showOnRankings: "Aparecer en los rankings",
      AppStrings.accountSectionTitle: "Cuenta",
      AppStrings.logoutButton: "Salir",
      AppStrings.logoutConfirmTitle: "¿Salir de Invest Game?",
      AppStrings.logoutConfirmMessage: "¿Seguro que deseas cerrar tu sesión?",
      AppStrings.cancelButton: "Cancelar",

      AppStrings.levelUpAchieved: "¡Nivel {level} alcanzado!",

      AppStrings.academyLevelLabel: "Inversor Nivel {level}",
      AppStrings.academyXpEarnedLabel: "{xp} XP conseguidos en la Academia",
      AppStrings.academyContinueSectionLabel: "CONTINUAR",
      AppStrings.academyXpToCompleteLabel: "+{xp} XP al completar",
      AppStrings.academyStartLessonButton: "Comenzar Lección",
      AppStrings.academyModulesSectionLabel: "MÓDULOS",
      AppStrings.academyLessonsSectionLabel: "LECCIONES",
      AppStrings.academyLessonsProgressLabel: "{completed} / {total} lecciones",
      AppStrings.academyLessonCompleteTitle: "¡Lección Completada!",
      AppStrings.academyXpPill: "+{xp} XP",
      AppStrings.academyContinueButton: "Continuar",
      AppStrings.academyConcludeButton: "Concluir",
      AppStrings.academyBackToAcademyButton: "Volver a la Academia",
      AppStrings.academyModuleStatusCompleted: "MÓDULO COMPLETADO",
      AppStrings.academyModuleStatusInProgress: "EN CURSO",
      AppStrings.academyModuleStatusAvailable: "DISPONIBLE",
      AppStrings.academyModuleStatusComingSoon: "PRÓXIMAMENTE",
      AppStrings.academyModuleStatusLocked: "BLOQUEADO",
      AppStrings.academySchoolsSectionLabel: "RECORRIDO",
      AppStrings.academyDomainsSectionLabel: "ESCUELAS",
      AppStrings.academyCatalogErrorTitle: "No se pudo cargar la Academia",
      AppStrings.academyCatalogErrorBody: "Verifica tu conexión e inténtalo de nuevo.",
      AppStrings.academyMasterySectionLabel: "TU MAESTRÍA",
      AppStrings.academyMasteryPercentLabel: "{percent}% completado",
      AppStrings.academyKnowledgeLevelLabel: "Progreso de conocimiento: {tier}",
      AppStrings.academyMicroExerciseLabel: "EJERCICIO RÁPIDO",
      AppStrings.academyApplyLabel: "APLICA LO QUE APRENDISTE",
      AppStrings.academyCorrectFeedbackTitle: "¡Exacto!",
      AppStrings.academyIncorrectFeedbackTitle: "¡Casi! Vamos a entender:",

      AppStrings.academyProgressLabel: "Progreso",
      AppStrings.academyRealMasteryLabel: "Maestría",
      AppStrings.masteryTierExploring: "Explorando",
      AppStrings.masteryTierUnderstanding: "Entendiendo",
      AppStrings.masteryTierApplying: "Aplicando",
      AppStrings.masteryTierMastering: "Dominando",

      AppStrings.academyRecommendedSectionLabel: "RECOMENDADO PARA TI",
      AppStrings.academyRecommendationContinueReason: "El siguiente paso de tu recorrido",
      AppStrings.academyRecommendationReviewReason: "Fallaste una pregunta aquí — vale la pena repasar",
      AppStrings.academyReviewCardTitle: "Repaso de hoy",
      AppStrings.academyReviewCardSubtitle: "{count} lecciones · ~{minutes} min",
      AppStrings.academyReviewStartButton: "Comenzar repaso",
      AppStrings.academyReviewEmptyState: "Todo al día — nada que repasar por ahora.",

      AppStrings.financialLabSectionLabel: "LABORATORIO FINANCIERO",
      AppStrings.financialLabTitle: "Laboratorio Financiero",
      AppStrings.financialLabSubtitle: "Simula escenarios y mira los conceptos en acción.",
      AppStrings.compoundInterestLabTitle: "Interés Compuesto",
      AppStrings.compoundInterestLabSubtitle: "Mira cómo el aporte, el plazo y la tasa cambian el resultado.",
      AppStrings.labComingSoon: "Próximamente",
      AppStrings.inflationLabTitle: "Inflación",
      AppStrings.fixedIncomeLabTitle: "Renta Fija",
      AppStrings.diversificationLabTitle: "Diversificación",
      AppStrings.portfolioLabTitle: "Cartera",
      AppStrings.labInitialAmountLabel: "Monto inicial",
      AppStrings.labMonthlyContributionLabel: "Aporte mensual",
      AppStrings.labAnnualReturnLabel: "Retorno anual",
      AppStrings.labYearsLabel: "Años",
      AppStrings.labFinalValueLabel: "Valor final",
      AppStrings.labTotalContributionsLabel: "Total invertido",
      AppStrings.labTotalGrowthLabel: "Total en rendimientos",
      AppStrings.labExplanationIncreaseYears:
          "Aumentar el plazo de {from} a {to} años amplió mucho el efecto del interés compuesto sobre el resultado.",
      AppStrings.labExplanationDecreaseYears:
          "Reducir el plazo de {from} a {to} años dejó menos tiempo para que actuara el interés compuesto.",
      AppStrings.labExplanationIncreaseReturn:
          "Aumentar el retorno anual de {from}% a {to}% aceleró el crecimiento de tu dinero con el tiempo.",
      AppStrings.labExplanationDecreaseReturn:
          "Reducir el retorno anual de {from}% a {to}% desaceleró el crecimiento de tu dinero con el tiempo.",
      AppStrings.labExplanationInitial: "Ajusta los valores para ver cómo cada variable cambia el resultado final.",
      AppStrings.labYearTooltipLabel: "Año {year}",

      AppStrings.appBarPlayerNamedGreeting: "{petName} · Nivel {level}",
      AppStrings.appBarPlayerGenericGreeting: "Nivel {level} · Explorador",
      AppStrings.profileTooltip: "Perfil",
      AppStrings.notificationsTooltip: "Notificaciones",
      AppStrings.logoutTooltip: "Salir",
      AppStrings.navHome: "Inicio",
      AppStrings.navWallet: "Cartera",
      AppStrings.navPassiveIncome: "Ingresos",
      AppStrings.navAcademy: "Academia",
      AppStrings.navMentor: "Mentor",
      AppStrings.homeContinueLearningEyebrow: "Misión de hoy",
      AppStrings.homeContinueLearningCta: "Continuar Aprendiendo",
      AppStrings.homeAllLessonsCompleteTitle: "¡Completaste todo por aquí!",
      AppStrings.homeAllLessonsCompleteBody: "Nuevos módulos llegan pronto. Explora la Academia para repasar lo que ya aprendiste.",
      AppStrings.homeExploreAcademyCta: "Ver Academia",
      AppStrings.homeLevelProgressLabel: "XP para el próximo nivel",
      AppStrings.homeNextEvolutionLabel: "XP para la próxima evolución",
      AppStrings.homeMaxEvolutionLabel: "Evolución máxima alcanzada",
      AppStrings.homeKnowledgeMapLabel: "TU RUTA DE CONOCIMIENTO",
      AppStrings.homeViewFullAcademyCta: "Ver ruta completa",
      AppStrings.homePortfolioBridgeLabel: "TU CARTERA",
      AppStrings.homePortfolioBridgeApplyMessage: "Ya completaste {count} lecciones — mira cómo aplicar ese conocimiento en tu cartera real.",
      AppStrings.homeViewPortfolioCta: "Ver Cartera",
      AppStrings.homeAnswerInvestorProfileLink: "¿Aún no respondiste tu perfil de inversor? Responder ahora",
      AppStrings.levelTierBeginner: "Principiante",
      AppStrings.levelTierLearner: "Aprendiz",
      AppStrings.levelTierExplorer: "Explorador",
      AppStrings.levelTierInvestor: "Inversor",
      AppStrings.levelTierAnalyst: "Analista",
      AppStrings.levelTierStrategist: "Estratega",
      AppStrings.levelTierSpecialist: "Especialista",

      // Knowledge Progress tiers (curriculum completion, not XP)
      AppStrings.knowledgeLevelAbsoluteBeginner: "Principiante Absoluto",
      AppStrings.knowledgeLevelFinancialApprentice: "Aprendiz Financiero",
      AppStrings.knowledgeLevelFinancialOrganizer: "Organizador Financiero",
      AppStrings.knowledgeLevelFinancialProtector: "Protector Financiero",
      AppStrings.knowledgeLevelBeginnerInvestor: "Inversor Principiante",
      AppStrings.knowledgeLevelInvestor: "Inversor",
      AppStrings.knowledgeLevelAnalyst: "Analista",
      AppStrings.knowledgeLevelWealthBuilder: "Constructor de Patrimonio",
      AppStrings.knowledgeLevelFinancialStrategist: "Estratega Financiero",
      AppStrings.knowledgeLevelFinancialMaster: "Maestro Financiero",

      AppStrings.companionHeaderTooltip: "Abrir tu compañero",
      AppStrings.companionDismissTooltip: "Cerrar",
      AppStrings.companionInteractionTitle: "¿Cómo puedo ayudarte?",
      AppStrings.companionInteractionSubtitle: "Elige a dónde ir",
      AppStrings.companionInteractionLearn: "Aprender",
      AppStrings.companionInteractionPortfolio: "Cartera",
      AppStrings.companionInteractionProgress: "Progreso",
      AppStrings.companionActionContinue: "Continuar",
      AppStrings.companionActionViewPortfolio: "Ver Cartera",
      AppStrings.companionActionViewProgress: "Ver Progreso",
      AppStrings.companionHomeXpToNextLevel: "¡Solo {xp} XP para tu próximo nivel!",
      AppStrings.companionAcademyContinueLesson: "Estabas avanzando en \"{lessonTitle}\". ¿Continuar donde lo dejaste?",
      AppStrings.companionAcademyReviewDue: "Tienes {count} conceptos para repasar. ¿Reforzamos lo que ya aprendiste?",
      AppStrings.companionPortfolioDiversified: "Tu cartera está distribuida en {count} activos diferentes.",
      AppStrings.companionMentorNudge: "¿Tienes alguna duda sobre inversiones? Pregúntame lo que quieras.",
      AppStrings.companionProfileSummary: "Estás en el nivel {level} — {stage}.",
      AppStrings.companionEventLessonCompleted: "¡Muy bien! Completaste la lección.",
      AppStrings.companionEventXpGained: "¡+{xp} XP! Sigue así.",
      AppStrings.companionEventLevelUp: "¡Nivel {level} alcanzado! Estoy orgulloso de ti.",
      AppStrings.companionEventAchievementUnlocked: "¡Logro desbloqueado: {title}!",
      AppStrings.companionEventEvolved: "¡Evolucioné! Ahora soy {stage}.",
      AppStrings.companionEventDifficultyDetected: "Noté que fallaste algunas en {school}. ¿Repasamos juntos?",
      AppStrings.companionEventSchoolMastered: "¡Completaste todo lo disponible en {school}! ¡Muy bien!",

      AppStrings.forgotPasswordTitle: "Recuperar contraseña",
      AppStrings.forgotPasswordSubtitle: "Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.",
      AppStrings.forgotPasswordEmailHint: "Tu correo",
      AppStrings.forgotPasswordSendButton: "Enviar enlace",
      AppStrings.forgotPasswordConfirmationMessage: "Si existe una cuenta con ese correo, recibirás instrucciones en unos instantes.",
      AppStrings.forgotPasswordHaveCodeLink: "Ya tengo un código de restablecimiento",
      AppStrings.resetPasswordTitle: "Restablecer contraseña",
      AppStrings.resetPasswordSubtitle: "Pega el código que te enviamos por correo y elige una nueva contraseña.",
      AppStrings.resetPasswordTokenHint: "Código de restablecimiento",
      AppStrings.resetPasswordNewPasswordHint: "Nueva contraseña",
      AppStrings.resetPasswordSubmitButton: "Restablecer contraseña",
      AppStrings.resetPasswordSuccessMessage: "¡Contraseña restablecida con éxito! Inicia sesión con tu nueva contraseña.",
      AppStrings.resetPasswordMismatchError: "Las contraseñas no coinciden.",
      AppStrings.resetPasswordFieldsRequiredError: "Completa todos los campos.",

      AppStrings.wealthLegendPatrimony: "Patrimonio",
      AppStrings.wealthLegendInvested: "Invertido",
      AppStrings.wealthLegendAppliedValue: "Valor invertido",
      AppStrings.wealthLegendCapitalGain: "Ganancia de Capital",
      AppStrings.proventosLegendReceived: "Recibidos",
      AppStrings.proventosLegendExpected: "Por recibir",
      AppStrings.noAssetsRegisteredYet: "Ningún activo registrado todavía.",
      AppStrings.retryButtonLabel: "Intentar de nuevo",
      AppStrings.mentorNewChatTooltip: "Nueva conversación",
      AppStrings.mentorHistoryTooltip: "Historial",
      AppStrings.mentorConversationHistoryTitle: "Conversaciones",
      AppStrings.mentorNoConversationsTitle: "Aún no hay conversaciones",
      AppStrings.mentorNoConversationsSubtitle: "Tus conversaciones con el mentor aparecerán aquí.",
      AppStrings.mentorConversationsLoadError: "No pudimos cargar tus conversaciones.",
      AppStrings.mentorRenameConversationTitle: "Renombrar conversación",
      AppStrings.mentorRenameConversationHint: "Título de la conversación",
      AppStrings.mentorRenameConversationSave: "Guardar",
      AppStrings.mentorDeleteConversationTitle: "¿Borrar conversación?",
      AppStrings.mentorDeleteConversationConfirm: "Esta conversación y todos sus mensajes se eliminarán permanentemente.",
      AppStrings.mentorDeleteConversationButton: "Borrar",
      AppStrings.initialPortfolioTitle: "Portafolio Inicial",
      AppStrings.portfolioCardTitle: "Portafolio",
      AppStrings.profileTitle: "Perfil",
      AppStrings.petTeacherAskMentor: "Pregúntale al mentor:",
      AppStrings.petTeacherOwnedGreeting: "¡Vamos a entender mejor {assetName}!",
      AppStrings.petTeacherNotOwnedGreeting: "¿Quieres saber más sobre {assetName}?",
    },
  };

  /// [params] fills `{token}` placeholders in the translated string (e.g.
  /// `{petName}`) — used for copy that embeds the user's chosen pet name,
  /// which can't be baked into the static translation map.
  static String translate(String key, {Map<String, String>? params}) {
    var value = _localizedValues[currentLanguage]?[key] ?? _localizedValues[defaultLanguage]?[key] ?? key;
    if (params != null) {
      for (final entry in params.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }
    return value;
  }
}
